[package]
name = "mlir_dialect_template"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
melior = "0.18.6"
mlir-sys = "0.2.2"

[build-dependencies]
bindgen = "0.70.1"
cmake = "0.1.51"
